_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 
  MASK_ON: True
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ("doclaynet_train",)
  TEST: ("doclaynet_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  STEPS: (225000, 275000)
  MAX_ITER: 300000
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "finetuning/output/doclaynet/mask_rcnn/rn50"